inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

# 標準の規約 + Railsの規約
Rails:
  Enabled: true

AllCops:
  # ルールをバージョンアップと同時に有効化
  NewCops: enable
  # Rubyのバージョンを指定
  TargetRubyVersion: 2.6.3p62
  # 指摘に対応するスタイルガイドのリンクを表示
  DisplayStyleGuide: true
  # スタイルガイドのリンクを日本語版に変換
  StyleGuideBaseURL: https://github.com/fortissimo1997/ruby-style-guide/blob/japanese/README.ja.md
  # 除外するファイル
  Exclude:
    - vendor/**/*
    - bin/*
    - db/**/*
    - config/**/*

# Missing magic comment # frozen_string_literal: true. を無視
Style/FrozenStringLiteralComment:
  Enabled: false

# Use nested module/class definitions instead of compact style. を無視
Style/ClassAndModuleChildren:
  Enabled: false

# Use only ascii symbols in comments. を無視
Style/AsciiComments:
  Enabled: false

# Unused method argument. を無視
Lint/UnusedMethodArgument:
  Enabled: false

# Missing top-level class documentation comment. を無視
Style/Documentation:
  Enabled: false

# hadowing outer local variable.  を無視
Lint/ShadowingOuterLocalVariable:
  Enabled: false

# Do not use block comments. を無視
Style/BlockComments:
  Enabled: false

# is not explicitly defined on the class. を無視
Rails/LexicallyScopedActionFilter:
  Enabled: false

# Do not write to stdout. Use Rails's logger if you want to log. を無視
Rails/Output:
  Enabled: false

# Block has too many lines. を無視
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

# Maximum example group nesting exceeded. を無視
RSpec/NestedGroups:
  Enabled: false

# Do not use expect() without .to or .not_to. Chain the methods or remove it. を無視
RSpec/VoidExpect:
  Enabled: false

# Useless assignment to variable - user. Did you mean user2? を無視
Lint/UselessAssignment:
  Exclude:
  - 'spec/**/*'

# Start context description with 'when', 'with', or 'without'. を無視
RSpec/ContextWording:
  Exclude:
  - 'spec/**/*'

# Example has too many lines. を無視
RSpec/ExampleLength:
  Enabled: false

# Example has too many expectations. を無視
RSpec/MultipleExpectations:
  Enabled: false
