inherit_from:
  - .rubocop_todo1.yml



#「inherit_from:」の記述によりrubocop_todo.ymlのファイルもrubocopコマンド実行時に参照する



#gemでインストールしたrubocopの設定をrubocopに適用する
require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  #デフォルト値をすべて無効に設定
  DisabledByDefault: true
  # ルールをバージョンアップと同時に有効化
  NewCops: enable
  TargetRubyVersion: 2.6.3p62
  # 指摘に対応するスタイルガイドのリンクを表示
  DisplayStyleGuide: true
  # スタイルガイドのリンクを日本語版に変換
  StyleGuideBaseURL: https://github.com/fortissimo1997/ruby-style-guide/blob/japanese/README.ja.md
  # 除外するファイル
  Exclude:
    - vendor/**/*
    - bin/*
    - db/**/*
    - config/**/*

#Rails関係のルールを有効
Rails:
  Enabled: true

#bundler関係のルールを有効。
Bundler:
  Enabled: true

#Gemspec関係のルールを有効。
Gemspec:
  Enabled: true

#Layout関係のルールを有効。
Layout:
  Enabled: true

#Lint関係のルールを有効。
Lint:
  Enabled: true

#Metrics関係のルールを有効。
Metrics:
  Enabled: true

#Performance関係のルールを有効。
Performance:
  Enabled: true

Security:
  Enabled: true

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

#一行の最大文字数設定
#Max: 120 でリファクタリングの必要あり。
Layout/LineLength:
  Enabled: true
  Max: 150

#|ABC|の値を最大30とする設定ABCSizeとは以下。https://qiita.com/yhorikawa/items/0fee9a380934fb29b016
# rubocop:disable Metrics/AbcSize  rubocop:enable Metrics/AbcSize で囲む事で無効の状態。
# 検索キーワード"rubocopを一時的に無効にする。"
Metrics/AbcSize:
  Max: 30

#モジュール内の最大行数
Metrics/ModuleLength:
  Max: 500

#メソッド内の最大行数
# rubocop:disable Metrics/MethodLength  rubocop:enable Metrics/MethodLength で囲む事で無効の状態。
# 検索キーワード"rubocopを一時的に無効にする。"
Metrics/MethodLength:
  CountComments: false
  Max: 50

#クラス内の最大行数
Metrics/ClassLength:
  CountComments: false
  Max: 500

#循環的複雑度の設定 デフォルトだと小さいので変更 Max20以下が適切か
#1~10 リクスなし/ 11~20 中リスク / 21~50 高リクス / 51以上 非常に高いリスク
#https://qiita.com/yut_arrows/items/16749e02313109071338
# rubocop:disable Metrics/CyclomaticComplexity  rubocop:enable Metrics/CyclomaticComplexity で囲む事で無効の状態。
# 検索キーワード"rubocopを一時的に無効にする。"
Metrics/CyclomaticComplexity:
  Max: 15

#if/caseなどのガード節を用いた複雑度の設定
#特に基準値がなかったため、循環的複雑度と同じ設定を適応
#詳しくはhttps://docs.rubocop.org/rubocop/cops_metrics.html
#ガード節とはhttps://ichi-station.com/%E3%82%AC%E3%83%BC%E3%83%89%E7%AF%80%E3%81%AB%E9%96%A2%E3%81%97%E3%81%A6/
# rubocop:disable Metrics/PerceivedComplexity  rubocop:enable Metrics/PerceivedComplexity で囲む事で無効の状態。
# 検索キーワード"rubocopを一時的に無効にする。"
Metrics/PerceivedComplexity:
  Max: 15

#ブロック内の行数を最大値以下とする設定をspec/**/*は除外
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

#befor_action等のonly、exceptオプションで指定されているメソッドが存在していなければならない設定を無効
Rails/LexicallyScopedActionFilter:
  Enabled: false

#putsやprintなどの出力はRailsのロガーを使わなければいけない設定を無効にする
Rails/Output:
  Enabled: false

#RuboCopを実行した際にRails/UniqueValidationWithoutIndex Cop（RuboCopのルールの一つ）に関するエラーを無効化
Rails/UniqueValidationWithoutIndex:
  Enabled: false

#ActiveRecord::Schema.defineブロックが設定された行数の上限を超過していることによるエラーを無効化
Metrics/BlockLength:
  Exclude:
    - 'db/schema.rb'