# fly.toml app configuration file generated for horenso-app on 2024-01-07T22:22:44+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "horenso-app"
primary_region = "nrt"
console_command = "/myproject/bin/rails console"

[build]
  dockerfile = "Dockerfile.prod"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024

[[statics]]
  guest_path = "/myproject/public"
  url_prefix = "/"
