name: Run RSpec

on:
  pull_request:
    branches: [ develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup docker
      shell: bash
      run: |
        # イメージのビルド
        docker-compose build
        # データベースの作成
        docker-compose run app bin/rails db:create
      env:
        RAILS_ENV: test

    - name: Run Test
      shell: bash
      run:  |
        docker-compose run app rubocop
        docker-compose run app rspec
